language: php

php:
  - 7.1

before_script:
  - composer install -d data/

script:
  - data/vendor/bin/behat
  - data/vendor/bin/phploc data/src

  - cd data
  - phpunit

notifications:
  email:
    - kedorev@gmail.com