language: php

php:
  - 7.1

before_script:
  - php -v
  - composer install --no-interaction -d data/

script:
  - cd ./data
  - vendor/bin/behat -v
  - vendor/bin/phploc ./src

notifications:
  email:
    - kedorev@gmail.com