language: php

php:
  - 7.1

before_script:
  - composer install -d data/

script:
  - phpunit -c data
  - data/vendor/bin/behat
  - data/vendor/bin/phploc data/src

notifications:
  email:
    - kedorev@gmail.com