<?php

namespace MainAppBundle\Repository;

/**
 * ModelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ModelsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllModelByFaction(string $faction)
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder();
        $query->select('m');
        $query->from("MainAppBundle:Models",'m');
        $query->innerJoin('m.factionKeyWord','f');
        $query->where("f.name = :faction");
        $query->setParameter("faction",$faction);
        return $query->getQuery()->getResult();
    }
}
