<?php

namespace MainAppBundle\Repository;

/**
 * ModelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelsRepository extends \Doctrine\ORM\EntityRepository
{
}
