<?php

namespace MainAppBundle\Repository;

/**
 * WeaponSwitchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeaponSwitchRepository extends \Doctrine\ORM\EntityRepository
{
}
